### ISSUE TITLE
UI improvements review

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/WebfontKitGenerator#10]
Hey, @bertob, sorry for bothering you. I'm making some UI improvements here and maybe you could help me solve some doubts.

I have updated the empty view to use `HdyStatusPage`, but it looks odd to me, any suggestions?
![Captura de pantalla de 2021-02-21 13-19-48](https://user-images.githubusercontent.com/6210397/108634768-26f5a700-7449-11eb-9b19-674029f3bd3f.png)

Also I have moved the directory selection to the fonts view.
![Captura de pantalla de 2021-02-21 13-26-05](https://user-images.githubusercontent.com/6210397/108634765-23fab680-7449-11eb-8d54-710babae66f0.png)

The finish view is also using `HdyStatusPage`, but looks like it always require an icon. Which icon should I use? `emblem-ok-symbolic`? `emblem-default-symbolic`?
![Captura de pantalla de 2021-02-21 13-20-18](https://user-images.githubusercontent.com/6210397/108634772-2a892e00-7449-11eb-9a36-ea29348ed567.png)

**Comment by rafaelmardojai** [comment]
Also since this app is a simple utility I have avoided it, but should I use `HdyViewSwitcher`?

**Comment by bertob** [comment]
> I have updated the empty view to use HdyStatusPage, but it looks odd to me, any suggestions?

Was there anything wrong with the old empty state?

If you do wanna go the HdyStatusPage route I'd use the hicolor app icon, and add more vertical spacing above the button.

> Which icon should I use? emblem-ok-symbolic? emblem-default-symbolic?

I'd go with the latter.

> Also since this app is a simple utility I have avoided it, but should I use HdyViewSwitcher?

It's a borderline case, but I think it'd be ok to use it here, seeing as it is the main app navigation.

**Comment by rafaelmardojai** [comment]
> Was there anything wrong with the old empty state?

Nope, I just wanted it to look uniform with other apps. Maybe I should keep the old empty state and update the label style.

**Comment by rafaelmardojai** [comment]
@bertob How looks now?

![Captura de pantalla de 2021-02-27 14-19-51](https://user-images.githubusercontent.com/6210397/109398116-a4695d80-7908-11eb-8cc0-e4b7e68ea9d3.png)
![Captura de pantalla de 2021-02-27 14-27-06](https://user-images.githubusercontent.com/6210397/109398117-a59a8a80-7908-11eb-9467-f14b6d98f744.png)

**Comment by bertob** [comment]
I'd maybe use `emblem-system` for the options tab, but lgtm otherwise :+1:

**Comment by rafaelmardojai** [comment]
> I'd maybe use emblem-system for the options tab, but lgtm otherwise

Done, I'm closing this now. Thanks for taking the time!
