### ISSUE TITLE
Error running v0.3.0 from source in Linux Mint 20

### ISSUE THREAD

**Issue by apandada1** [rafaelmardojai/WebfontKitGenerator#13]
I installed `webfontkitgenerator` (v0.3.0, not latest git branch) on a new computer running Linux Mint 20 from the PPA, and it showed this following error. 
Then I installed it from source, and the same error occurs.

The strange thing is, I have the same version of webfontkitgenerator installed in another computer running Linux Mint 20 (on which I made the debian package), and it works perfectly there. Any idea?

```
$ /home/archisman/.local/bin/webfontkitgenerator
Traceback (most recent call last):
  File "/home/archisman/.local/bin/webfontkitgenerator", line 47, in <module>
    sys.exit(main.main(VERSION))
  File "/home/archisman/.local/share/webfontkitgenerator/webfontkitgenerator/main.py", line 63, in main
    app = Application(version)
  File "/home/archisman/.local/share/webfontkitgenerator/webfontkitgenerator/main.py", line 42, in __init__
    GObject.type_register(Handy.Column)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 131, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Handy' object has no attribute 'Column'
```

I have libhandy `1.0.0-0` installed (in both the computers).

By any chance, am I missing any other dependency? It may happen that some dependency is manually installed in the other computer, but is missing in this new computer, which is causing this issue (it seems that the installation of `libhandy 1.0.0` is _not_ corrupted, because `blanket` (debian package) works fine, while `webfontkitgenerator` does not). I did install fonttools and brotli, they are most likely not the culprit.

**Comment by rafaelmardojai** [comment]
`v0.3.0` was written with libhandy alpha `0.0` that's the issue, libhandy `1.0` included a lot of api changes.

**Comment by apandada1** [comment]
It looks for Handy-1 when libhandy-1 is not installed. I guess it does depend on libhandy-1.

**Comment by rafaelmardojai** [comment]
Yes, WebfontKitGenerator `v0.3.0` was written with libhandy `v0.81.0`, and since libhandy `v0.80.0` the API was bumped to `1.0.0` ([see release notes](https://gitlab.gnome.org/GNOME/libhandy/-/releases/v0.80.0)). That's why `main.py` from  `v0.3.0` explicity requires `libhandy-1` with `gi.require_version('Handy', '1')`.

The problem is that libhandy `1.0.0` changed the name of a lot of widgets, like `HdyColumn` to `HdyClamp`.

**Comment by apandada1** [comment]
I see. I wonder how that still works in the other computer, but anyway.

I guess the PPA users need to wait till Ubuntu catches up with a recent enough version of libhandy, and till libhandy APIs stabilize.
The flatpak works. :+1:

**Comment by apandada1** [comment]
Finally, works in Ubuntu 21.04 (soon to be released) with libhandy1.2

**Comment by rafaelmardojai** [comment]
Nice, I will release the new version this week.
