### ISSUE TITLE
Locale error on launching

### ISSUE THREAD

**Issue by WolfangT** [rafaelmardojai/WebfontKitGenerator#19]
I get this error on launching, installed using Pop!_Shop and flatpak commands,both produce the same output:

$/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=webfontkitgenerator com.rafaelmardojai.WebfontKitGenerator
  Traceback (most recent call last):
    File "/app/bin/webfontkitgenerator", line 37, in <module>
      locale.setlocale(locale.LC_ALL, '')
    File "/usr/lib/python3.7/locale.py", line 604, in setlocale
      return _setlocale(category, locale)
  locale.Error: unsupported locale setting

Data from my system:

$ localectl status
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=es_VE.UTF-8
                  LC_TIME=es_VE.UTF-8
                  LC_MONETARY=es_VE.UTF-8
                  LC_PAPER=es_VE.UTF-8
                  LC_NAME=es_VE.UTF-8
                  LC_ADDRESS=es_VE.UTF-8
                  LC_TELEPHONE=es_VE.UTF-8
                  LC_MEASUREMENT=es_VE.UTF-8
                  LC_IDENTIFICATION=es_VE.UTF-8
       VC Keymap: us
      X11 Layout: us

$ cat /etc/os-release
  NAME="Pop!_OS"
  VERSION="20.10"
  ID=pop
  ID_LIKE="ubuntu debian"
  PRETTY_NAME="Pop!_OS 20.10"
  VERSION_ID="20.10"
  HOME_URL="https://pop.system76.com"
  SUPPORT_URL="https://support.system76.com"
  BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
  PRIVACY_POLICY_URL="https://system76.com/privacy"
  VERSION_CODENAME=groovy
  UBUNTU_CODENAME=groovy
  LOGO=distributor-logo-pop-os

**Comment by WolfangT** [comment]
Manually comented line 37 in my local isntalation:

~/.local/share/flatpak/app/com.rafaelmardojai.WebfontKitGenerator/current/active/files/bin/webfontkitgenerator

and it runs fine and genreates the font and css files. it does return this warning:

(webfontkitgenerator:2): Gtk-WARNING **: 15:26:18.652: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 15:26:18.653: Failed to load module "appmenu-gtk-module"

Great software btw, very usefull and nice locking

**Comment by rafaelmardojai** [comment]
Yep, I forgotten to remove that line, thanks for the report.

I'm releasing a new version these days, so the fix will arrive to flathub soon.
