### ISSUE TITLE
Make welcome screen illustration recolorable

### ISSUE THREAD

**Issue by bertob** [rafaelmardojai/WebfontKitGenerator#3]
Currently the illustration on the welcome screen doesn't recolor to the normal text color like a symbolic icon would. It'd be nicer if it did, IIRC all you need to do is add `-symbolic` to its name.

**Comment by rafaelmardojai** [comment]
It only seems to work if I handle it as an icon and not as a normal resource.

The problem is that it will use wrong proportions:

![Captura de pantalla de 2020-06-02 10-32-34](https://user-images.githubusercontent.com/6210397/83539261-6dbaff80-a4bc-11ea-887b-b4b59c4ab061.png)

**Comment by bertob** [comment]
Ah interesting, so it forces it to be a square? I guess that could be made to work, if we could center the illustration vertically on the square.

**Comment by rafaelmardojai** [comment]
I have made the SVG square and centered the illustration vertically. 

I have also removed the spacing between elements,  but i think it stills too spacious.

![Captura de pantalla de 2020-06-02 16-01-27](https://user-images.githubusercontent.com/6210397/83569707-84784b00-a4ea-11ea-8915-930a8b861185.png)

**Comment by bertob** [comment]
Yeah, agreed. I guess a potential alternative could be splitting the illustration up into two separate square ones side by side?

**Comment by rafaelmardojai** [comment]
I think it works well

![Captura de pantalla de 2020-06-02 16-39-01](https://user-images.githubusercontent.com/6210397/83572671-98727b80-a4ef-11ea-8401-76e1f145b94f.png)
